### ISSUE TITLE
1 day time frame

### ISSUE THREAD

**Issue by Digiguy1** [n3m6/Sessa#3]
hi i been playing around with the bot i really like it but is there a way to change the time frame from 15min to 1d or to daily time frame ??

**Comment by n3m6** [comment]
Hi. Late reply, sorry.

In theory it's possible to add a 1d timeframe to the data stream reader, but it's better to write a script that wakes up once a day and polls their webservice instead of consuming resources all day. That is more reliable too, since the stream occasionally has interruptions and breaks. So, no, the bot doesn't have a 1d time frame yet.
